// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: files.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createFile = `-- name: CreateFile :one
INSERT INTO files (upload_id,name)
VALUES ($1,$2)
RETURNING  id, name, pages, upload_id
`

type CreateFileParams struct {
	UploadID uuid.UUID `json:"upload_id"`
	Name     string    `json:"name"`
}

func (q *Queries) CreateFile(ctx context.Context, arg CreateFileParams) (File, error) {
	row := q.db.QueryRow(ctx, createFile, arg.UploadID, arg.Name)
	var i File
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Pages,
		&i.UploadID,
	)
	return i, err
}

const createFilesBatch = `-- name: CreateFilesBatch :many
WITH idx AS (
    SELECT generate_series(1, array_length($1::text[], 1)) AS i
),
ins AS (
    INSERT INTO files (upload_id, name, pages)
    SELECT
        $2::uuid AS upload_id,
        ($1::text[])[i] AS name,
        $3::int AS pages
    FROM idx
    RETURNING id, upload_id, name, pages
)
SELECT id, upload_id, name, pages FROM ins
`

type CreateFilesBatchParams struct {
	Names    []string  `json:"names"`
	UploadID uuid.UUID `json:"upload_id"`
	Pages    int32     `json:"pages"`
}

type CreateFilesBatchRow struct {
	ID       uuid.UUID   `json:"id"`
	UploadID uuid.UUID   `json:"upload_id"`
	Name     string      `json:"name"`
	Pages    pgtype.Int4 `json:"pages"`
}

func (q *Queries) CreateFilesBatch(ctx context.Context, arg CreateFilesBatchParams) ([]CreateFilesBatchRow, error) {
	rows, err := q.db.Query(ctx, createFilesBatch, arg.Names, arg.UploadID, arg.Pages)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CreateFilesBatchRow{}
	for rows.Next() {
		var i CreateFilesBatchRow
		if err := rows.Scan(
			&i.ID,
			&i.UploadID,
			&i.Name,
			&i.Pages,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteFilesdByUploadId = `-- name: DeleteFilesdByUploadId :one
DELETE FROM files
WHERE upload_id = $1
RETURNING  id, name, pages, upload_id
`

func (q *Queries) DeleteFilesdByUploadId(ctx context.Context, uploadID uuid.UUID) (File, error) {
	row := q.db.QueryRow(ctx, deleteFilesdByUploadId, uploadID)
	var i File
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Pages,
		&i.UploadID,
	)
	return i, err
}

const getAllFiles = `-- name: GetAllFiles :many
SELECT id, name, pages, upload_id
FROM files
LIMIT $1
OFFSET $2
`

type GetAllFilesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) GetAllFiles(ctx context.Context, arg GetAllFilesParams) ([]File, error) {
	rows, err := q.db.Query(ctx, getAllFiles, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []File{}
	for rows.Next() {
		var i File
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Pages,
			&i.UploadID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFilesByName = `-- name: GetFilesByName :many
SELECT id, name, pages, upload_id
FROM files
WHERE name = $1
`

func (q *Queries) GetFilesByName(ctx context.Context, name string) ([]File, error) {
	rows, err := q.db.Query(ctx, getFilesByName, name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []File{}
	for rows.Next() {
		var i File
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Pages,
			&i.UploadID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFilesByUploadId = `-- name: GetFilesByUploadId :many
SELECT id, name, pages, upload_id
FROM files
WHERE upload_id = $1
`

func (q *Queries) GetFilesByUploadId(ctx context.Context, uploadID uuid.UUID) ([]File, error) {
	rows, err := q.db.Query(ctx, getFilesByUploadId, uploadID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []File{}
	for rows.Next() {
		var i File
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Pages,
			&i.UploadID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateFile = `-- name: UpdateFile :one
UPDATE files
SET pages = $2
WHERE upload_id = $1
RETURNING  id, name, pages, upload_id
`

type UpdateFileParams struct {
	UploadID uuid.UUID   `json:"upload_id"`
	Pages    pgtype.Int4 `json:"pages"`
}

func (q *Queries) UpdateFile(ctx context.Context, arg UpdateFileParams) (File, error) {
	row := q.db.QueryRow(ctx, updateFile, arg.UploadID, arg.Pages)
	var i File
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Pages,
		&i.UploadID,
	)
	return i, err
}
