pub const RABBITMQ_HOST: &str = "RABBITMQ_HOST";
pub const TRANSFORM_QUEUE: &str = "TRANSFORM_QUEUE";
pub const PROCESSED_QUEUE: &str = "PROCESSED_QUEUE";
pub const UPLOAD_DIR: &str = "UPLOAD_DIR";
pub const CONCURRENT_BATCHES: &str = "CONCURRENT_BATCHES";
