FROM golang:1.24-bullseye AS build
WORKDIR /app

COPY . . 

RUN go build -o main ./main.go

RUN go mod tidy

FROM ubuntu:24.04

RUN apt-get update && \
    apt-get install -y --no-install-recommends libreoffice && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY --from=build /app/main .

EXPOSE 8080

CMD ["./main"]
