# syntax=docker/dockerfile:1

FROM golang:1.24-bullseye AS build
WORKDIR /app

COPY go.mod go.sum app.env ./
RUN go mod download

COPY . .
RUN go build -o main ./cmd/app/main.go

FROM ubuntu:24.04

RUN apt-get update && \
    apt-get install -y --no-install-recommends libreoffice && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

ENV UNO_JAVA_JFW_DISABLE=true

WORKDIR /app
COPY --from=build /app/main  /app/app.env ./
CMD ["./main"]
