FROM golang:1.24-bullseye AS build
WORKDIR /app

COPY go.mod go.sum app.env ./
RUN go mod download

COPY . .
RUN go build -o main ./cmd/app/main.go

FROM alpine:3.19

RUN apk add --no-cache imagemagick

WORKDIR /app
COPY --from=build /app/main  /app/app.env ./
CMD ["./main"]
