FROM golang:1.24-bullseye AS build

WORKDIR /app

# Copy app file where it actually lives
COPY document_processor/go.work ./document_processor/

# Copy module files
COPY common ./common
COPY document_processor/go.mod document_processor/go.sum ./document_processor/

# Run go commands FROM the app module directory
WORKDIR /app/document_processor

RUN go work sync
RUN go mod download all

# Copy source
COPY document_processor ./


RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 \
    go build -o /app/main ./cmd/app

# ---------- runtime stage ----------
FROM alpine:3.19

RUN apk add --no-cache \
    imagemagick \
    ghostscript \
    libpng \
    libjpeg-turbo \
    freetype

# Enable PDF read/write
RUN sed -i \
    's/rights="none" pattern="PDF"/rights="read|write" pattern="PDF"/' \
    /etc/ImageMagick-*/policy.xml

WORKDIR /app

COPY --from=build /app/main ./
COPY --from=build /app/document_processor/app.env ./

CMD ["./main"]
