FROM golang:1.24-bullseye AS build

WORKDIR /app

# Copy app file where it actually lives
COPY conversion_service/go.work ./conversion_service/

# Copy module files
COPY common ./common
COPY conversion_service/go.mod conversion_service/go.sum ./conversion_service/

# Run go commands FROM the app module directory
WORKDIR /app/conversion_service

RUN go work sync
RUN go mod download all

# Copy source
COPY conversion_service ./


RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 \
    go build -o /app/main ./cmd/app

# ---------- runtime stage ----------
FROM alpine:3.19

RUN apk add --no-cache \
    imagemagick \
    ghostscript \
    libpng \
    libjpeg-turbo \
    freetype

# Enable PDF read/write
RUN sed -i \
    's/rights="none" pattern="PDF"/rights="read|write" pattern="PDF"/' \
    /etc/ImageMagick-*/policy.xml

WORKDIR /app

COPY --from=build /app/main ./
COPY --from=build /app/conversion_service/app.env ./

CMD ["./main"]
