FROM golang:1.24 AS build

WORKDIR /app

COPY . .

RUN go mod tidy

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o main ./cmd/main.go

FROM alpine:3.21

WORKDIR /app

COPY --from=build /app/main /app/src/

COPY ./docs /app/docs
COPY ./app.env /app/app.env

WORKDIR /app/src

CMD ["./main"]
