FROM golang:1.24 AS builder

WORKDIR /app

COPY . .
RUN go mod download


RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o main ./cmd/api/main.go

FROM alpine:3.21

WORKDIR /app

COPY --from=builder /app/main /app/main

COPY app.env /app/app.env
COPY internal/db/migrations /app/internal/db/migrations

COPY docs /app/docs

CMD ["./main"]
